"""add_reward_ledger_unique_constraint

Revision ID: 018736304309
Revises: d13ba80d3881
Create Date: 2026-05-19 23:19:33.257725
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '018736304309'
down_revision: str | None = 'd13ba80d3881'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_reward_source', 'reward_ledger', ['source_type', 'source_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_reward_source', 'reward_ledger', type_='unique')
    # ### end Alembic commands ###
