"""add_redemptions

Revision ID: 0830247bf543
Revises: 08906cd65096
Create Date: 2026-05-20 13:27:57.950731
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '0830247bf543'
down_revision: str | None = '08906cd65096'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('redemptions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('child_id', sa.Uuid(), nullable=False),
    sa.Column('shop_item_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ),
    sa.ForeignKeyConstraint(['shop_item_id'], ['shop_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_redemptions_child_id'), 'redemptions', ['child_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_redemptions_child_id'), table_name='redemptions')
    op.drop_table('redemptions')
    # ### end Alembic commands ###
