"""add_shop_stock_fulfilled

Revision ID: 08906cd65096
Revises: c1fdf30d9b94
Create Date: 2026-05-20 12:57:11.270950
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '08906cd65096'
down_revision: str | None = 'c1fdf30d9b94'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shop_items', sa.Column('stock', sa.Integer(), nullable=True))
    op.add_column('shop_items', sa.Column('fulfilled_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shop_items', 'fulfilled_at')
    op.drop_column('shop_items', 'stock')
    # ### end Alembic commands ###
