"""add_streak_threshold

Revision ID: 2e91aa6e2a1c
Revises: 7833dec3ae29
Create Date: 2026-05-21 03:52:48.747131
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '2e91aa6e2a1c'
down_revision: str | None = '7833dec3ae29'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('children', sa.Column('streak_threshold', sa.Integer(), nullable=False, server_default='80'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('children', 'streak_threshold')
    # ### end Alembic commands ###
