"""add_scheduled_time_to_daily_tasks

Revision ID: 38c0472cb324
Revises: d2757bfdc722
Create Date: 2026-05-18 13:30:16.150371
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '38c0472cb324'
down_revision: str | None = 'd2757bfdc722'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_tasks', sa.Column('scheduled_start', sa.Time(timezone=True), nullable=True))
    op.add_column('daily_tasks', sa.Column('scheduled_end', sa.Time(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('daily_tasks', 'scheduled_end')
    op.drop_column('daily_tasks', 'scheduled_start')
    # ### end Alembic commands ###
