"""add_streak_updated_date

Revision ID: 3a1b5c7d9e2f
Revises: 2e91aa6e2a1c
Create Date: 2026-05-23 17:30:00.000000
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '3a1b5c7d9e2f'
down_revision: str | None = '2e91aa6e2a1c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('streaks', sa.Column('streak_updated_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('streaks', 'streak_updated_date')
    # ### end Alembic commands ###
