"""add_redemption_status

Revision ID: 7833dec3ae29
Revises: 0830247bf543
Create Date: 2026-05-20 14:26:10.509284
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '7833dec3ae29'
down_revision: str | None = '0830247bf543'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('redemptions', sa.Column('status', sa.String(length=20), nullable=False, server_default='pending'))
    op.add_column('redemptions', sa.Column('fulfilled_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('redemptions', 'fulfilled_at')
    op.drop_column('redemptions', 'status')
    # ### end Alembic commands ###
