"""add_shop_items

Revision ID: c1fdf30d9b94
Revises: 018736304309
Create Date: 2026-05-20 11:47:03.837700
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'c1fdf30d9b94'
down_revision: str | None = '018736304309'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shop_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('parent_id', sa.Uuid(), nullable=False),
    sa.Column('child_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('star_cost', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['parents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shop_items_child_id'), 'shop_items', ['child_id'], unique=False)
    op.create_index(op.f('ix_shop_items_parent_id'), 'shop_items', ['parent_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shop_items_parent_id'), table_name='shop_items')
    op.drop_index(op.f('ix_shop_items_child_id'), table_name='shop_items')
    op.drop_table('shop_items')
    # ### end Alembic commands ###
