"""add_username_password_to_parents

Revision ID: d13ba80d3881
Revises: e7696c2b69ee
Create Date: 2026-05-19 15:14:27.809021
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'd13ba80d3881'
down_revision: str | None = 'e7696c2b69ee'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parents', sa.Column('username', sa.String(length=80), nullable=True))
    op.add_column('parents', sa.Column('password_hash', sa.String(length=255), nullable=True))
    op.alter_column('parents', 'wechat_openid',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.create_unique_constraint(None, 'parents', ['username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'parents', type_='unique')
    op.alter_column('parents', 'wechat_openid',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.drop_column('parents', 'password_hash')
    op.drop_column('parents', 'username')
    # ### end Alembic commands ###
