"""add_child_task_template_unique

Revision ID: d24ff131a52d
Revises: 38c0472cb324
Create Date: 2026-05-18 14:20:58.871739
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'd24ff131a52d'
down_revision: str | None = '38c0472cb324'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_daily_task_template', 'daily_tasks', ['child_id', 'task_date', 'task_template_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_daily_task_template', 'daily_tasks', type_='unique')
    # ### end Alembic commands ###
