"""phase1-5_tasks_rewards

Revision ID: d2757bfdc722
Revises: fb02bbab2ea0
Create Date: 2026-05-18 11:57:07.008547
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'd2757bfdc722'
down_revision: str | None = 'fb02bbab2ea0'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_plans_child_status'), table_name='plans')
    op.drop_index(op.f('idx_reward_ledger_child_created'), table_name='reward_ledger')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_reward_ledger_child_created'), 'reward_ledger', ['child_id', 'created_at'], unique=False)
    op.create_index(op.f('idx_plans_child_status'), 'plans', ['child_id', 'status'], unique=False)
    # ### end Alembic commands ###
