"""add_created_by_approved_schedule_by

Revision ID: e7696c2b69ee
Revises: d24ff131a52d
Create Date: 2026-05-19 05:07:55.048726
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'e7696c2b69ee'
down_revision: str | None = 'd24ff131a52d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_tasks', sa.Column('created_by', sa.String(length=20), nullable=False, server_default='parent'))
    op.add_column('daily_tasks', sa.Column('approved', sa.Boolean(), nullable=False, server_default=sa.text('true')))
    op.add_column('daily_tasks', sa.Column('schedule_by', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('daily_tasks', 'schedule_by')
    op.drop_column('daily_tasks', 'approved')
    op.drop_column('daily_tasks', 'created_by')
    # ### end Alembic commands ###
