"""phase1_5_plan_tasks_streaks

Revision ID: fb02bbab2ea0
Revises: faa96427f011
Create Date: 2026-05-18 11:40:40.002252
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'fb02bbab2ea0'
down_revision: str | None = 'faa96427f011'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plans',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('parent_id', sa.Uuid(), nullable=False),
    sa.Column('child_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['parents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plans_child_id'), 'plans', ['child_id'], unique=False)
    op.create_index(op.f('ix_plans_parent_id'), 'plans', ['parent_id'], unique=False)
    op.create_table('reward_ledger',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('child_id', sa.Uuid(), nullable=False),
    sa.Column('source_type', sa.String(length=40), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=True),
    sa.Column('stars_delta', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=160), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reward_ledger_child_id'), 'reward_ledger', ['child_id'], unique=False)
    op.create_table('streaks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('child_id', sa.Uuid(), nullable=False),
    sa.Column('current_days', sa.Integer(), nullable=False),
    sa.Column('longest_days', sa.Integer(), nullable=False),
    sa.Column('last_completed_date', sa.Date(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_streaks_child_id'), 'streaks', ['child_id'], unique=True)
    op.create_table('task_templates',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('plan_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('expected_minutes', sa.Integer(), nullable=True),
    sa.Column('weekdays', sa.ARRAY(sa.Integer()), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('reward_stars', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_templates_plan_id'), 'task_templates', ['plan_id'], unique=False)
    op.create_table('daily_tasks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('child_id', sa.Uuid(), nullable=False),
    sa.Column('plan_id', sa.Uuid(), nullable=False),
    sa.Column('task_template_id', sa.Uuid(), nullable=True),
    sa.Column('task_date', sa.Date(), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('expected_minutes', sa.Integer(), nullable=True),
    sa.Column('reward_stars', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('child_feedback', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.ForeignKeyConstraint(['task_template_id'], ['task_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_tasks_child_id'), 'daily_tasks', ['child_id'], unique=False)
    op.create_index(op.f('ix_daily_tasks_plan_id'), 'daily_tasks', ['plan_id'], unique=False)
    op.create_index(op.f('ix_daily_tasks_task_date'), 'daily_tasks', ['task_date'], unique=False)
    op.create_index('idx_plans_child_status', 'plans', ['child_id', 'status'], unique=False)
    op.create_index('idx_reward_ledger_child_created', 'reward_ledger', ['child_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_daily_tasks_task_date'), table_name='daily_tasks')
    op.drop_index('idx_reward_ledger_child_created', table_name='reward_ledger')
    op.drop_index('idx_plans_child_status', table_name='plans')
    op.drop_index(op.f('ix_daily_tasks_plan_id'), table_name='daily_tasks')
    op.drop_index(op.f('ix_daily_tasks_child_id'), table_name='daily_tasks')
    op.drop_table('daily_tasks')
    op.drop_index(op.f('ix_task_templates_plan_id'), table_name='task_templates')
    op.drop_table('task_templates')
    op.drop_index(op.f('ix_streaks_child_id'), table_name='streaks')
    op.drop_table('streaks')
    op.drop_index(op.f('ix_reward_ledger_child_id'), table_name='reward_ledger')
    op.drop_table('reward_ledger')
    op.drop_index(op.f('ix_plans_parent_id'), table_name='plans')
    op.drop_index(op.f('ix_plans_child_id'), table_name='plans')
    op.drop_table('plans')
    # ### end Alembic commands ###
